"""empty message

Revision ID: 371303aa3c2f
Revises: 
Create Date: 2020-10-16 15:04:03.350149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371303aa3c2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('date_created', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('admin')
    # ### end Alembic commands ###
