"""Initial database migration

Revision ID: a0a29cdae2e4
Revises: 371303aa3c2f
Create Date: 2021-01-14 02:06:41.107477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a29cdae2e4'
down_revision = '371303aa3c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('date_created', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('admin')
    # ### end Alembic commands ###
